#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# BSPWM Config

bspc config focus_follows_pointer true
bspc config pointer_motion_interval 7ms

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gpick state = floating
bspc rule -a Nextcloud state = floating

# decoration

~/.config/themes/gruvbox/bspwm/bspwmrc
xsetroot -cursor_name left_ptr

# window rules

bspc rule -a Spotify -o desktop=^10  
bspc rule -a VSCodium -o desktop=^2  
bspc rule -a kitty -o desktop=^3  
bspc rule -a Thunar -o desktop=^9  

# launch polybar

~/.config/polybar/launch.sh 

# start stuff

~/.config/bspwm/autostart.sh
 
