#! /bin/sh

~/.config/bspwm/autostart.sh 

pgrep -x sxhkd > /dev/null || sxhkd &

# BSPWM Config

bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# decoration

/home/martin/.config/themes/gruvbox/bspwm/bspwmrc

# window rules

bspc rule -a Spotify -o desktop=^10
bspc rule -a Code -o desktop=^2
bspc rule -a kitty -o desktop=^3
bspc rule -a Thunar -o desktop=^9

# launch polybar

~/.config/polybar/launch.sh 

# start stuff

xsetroot -cursor_name left_ptr
dunst
xfce4-power-manager --daemon