#! /bin/sh

# set wallpaper

feh --bg-fill Dokumente/Backgrounds/gruvbox-wallpapers-main/wallpapers/mix/wallhaven-vmk698.jpg 

# Decoration

bspc config top_padding        45
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       3
bspc config window_gap         10

# Border colors

bspc config normal_border_color "#282c34"
bspc config focused_border_color "#4b716e"
bspc config urgent_border_color "#4b716e"
bspc config presel_border_color "#4b716e"