#! /bin/sh

# set wallpaper

feh --bg-fill ~/configs/wallpapers/FourSeasons.jpg

# Decoration

bspc config top_padding        57
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       5
bspc config window_gap         5

# Border colors

bspc config normal_border_color "#AE5858"
bspc config focused_border_color "#266B79"
bspc config urgent_border_color "#4b716e"
bspc config presel_border_color "#4b716e"